name: Deploy LookatDeez Functions (.NET 8)

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.204'
  PROJECT_FILE: 'LookatDeezBackend/LookatDeezBackend.csproj'
  PUBLISH_DIR: 'published'
  AZURE_FUNCTIONAPP_NAME: 'lookatdeez-functions'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Cache NuGet
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj','**/packages.lock.json') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Restore & Publish
        shell: bash
        run: |
          set -euo pipefail
          dotnet --version
          dotnet restore "${{ env.PROJECT_FILE }}"
          dotnet publish "${{ env.PROJECT_FILE }}" -c Release -o "${{ env.PUBLISH_DIR }}"

      - name: Verify Functions package layout (net8 isolated)
        shell: bash
        run: |
          set -euo pipefail
          echo "Publish dir contents:" && ls -la "${{ env.PUBLISH_DIR }}"
          test -f "${{ env.PUBLISH_DIR }}/host.json" || (echo "::error::host.json missing" && exit 1)

          META_FILE="${{ env.PUBLISH_DIR }}/functions.metadata"
          if [ -f "$META_FILE" ] && [ -s "$META_FILE" ]; then
            echo "OK: Found functions.metadata (net8 isolated)."
            head -c 200 "$META_FILE" >/dev/null 2>&1 || true
          else
            COUNT=$(find "${{ env.PUBLISH_DIR }}" -maxdepth 2 -name function.json | wc -l || true)
            if [ "$COUNT" -gt 0 ]; then
              echo "OK: Found $COUNT function.json file(s):"
              find "${{ env.PUBLISH_DIR }}" -maxdepth 2 -name function.json -print
            else
              echo "::error::No functions.metadata or function.json found. Ensure you have at least one [Function] and Worker.Sdk analyzer in the csproj."
              exit 1
            fi
          fi

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7535D8B89C4F4B719148B58C8FF35484 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BEF8E29C85F848A199ECD77A7B703DD6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_442E4247BBF54B478C9E86E6EFEB7D7F }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          slot-name: 'Production'
          package: ${{ env.PUBLISH_DIR }}
