name: Build and deploy Azure Functions (.NET 8)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.204'
  # CHANGE this if your csproj name is different:
  PROJECT_FILE: 'LookatDeezBackend/LookatDeezBackend.csproj'
  PUBLISH_DIR: 'published'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore & Publish
        shell: bash
        run: |
          dotnet --version
          dotnet restore "${{ env.PROJECT_FILE }}"
          dotnet publish "${{ env.PROJECT_FILE }}" \
            --configuration Release \
            --output "${{ env.PUBLISH_DIR }}"

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7535D8B89C4F4B719148B58C8FF35484 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BEF8E29C85F848A199ECD77A7B703DD6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_442E4247BBF54B478C9E86E6EFEB7D7F }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'lookatdeez-functions'     # your Function App name
          slot-name: 'Production'
          package: '${{ env.PUBLISH_DIR }}'
